site_name: KeyNotS
site_description: Quick References for Backend Dev Tools - Dox Portal
nav:
  - Home: index.md
  - DevOps:
      - Tools: devops/devops-tools.md
      - Linux: devops/linux.md
      - Docker: devops/docker.md
  - About: about.md
theme:
  name: material